CREATE OR REPLACE FUNCTION Func_Media(P1 IN NUMBER, P2 IN NUMBER) RETURN VARCHAR IS

   V_TOTAL NUMBER(2) := 0;

   V_SITUACAO  VARCHAR(20) := NULL;

BEGIN

   V_TOTAL := (P1 + P2)/2;

   IF V_TOTAL >= 5 THEN
      V_SITUACAO := 'APROVADO';
   ELSE
      V_SITUACAO := 'REPROVADO';
   END IF;   

   RETURN V_SITUACAO;
   
END;

-- SELECT fnc_media(6,6) FROM DUAL

-----------------
DECLARE
  V_RETORNO NUMBER(2):= 0;
BEGIN
  V_RETORNO := fnc_media(2,4);
  DBMS_OUTPUT.PUT_LINE('O RETORNO É: '||V_RETORNO);
END;