DECLARE
  CURSOR C_FUNC IS
    select nm_funcionario, id_genero, id_status from funcionarios;
  
  V_CONTADOR   NUMBER(3) := 0;
  V_USUARIO    VARCHAR(50) := NULL;
  V_DATA       DATE := NULL;
  V_NOME       VARCHAR(50) := NULL; 
  V_SITUACAO   VARCHAR(40) := NULL;
  V_GENERO     VARCHAR(20) := NULL;
  V_COUNT      NUMBER(3) := 0;
  V_COUNT_MASC NUMBER(3) := 0;
  V_COUNT_FEM  NUMBER(3) := 0;
  V_STATUS     VARCHAR(30) := NULL;
BEGIN
  SELECT USER, SYSDATE INTO V_USUARIO, V_DATA FROM DUAL;
  
  FOR R_FUNC IN C_FUNC LOOP
  
      V_NOME := R_FUNC.NM_FUNCIONARIO;
      
     --- IF R_FUNC.NM_FUNCIONARIO = 'CARLA SANTOS' THEN
     --- V_SITUACAO := 'ELA É LEGAL';
     --- ELSE
     --- V_SITUACAO := NULL;
     --- END IF;    
      
      -- IF GENERO
      IF R_FUNC.ID_GENERO  = 1 THEN
         V_GENERO := 'MASCULINO';
         
         V_COUNT_MASC := V_COUNT_MASC + V_COUNT_MASC;
      ELSE
         V_GENERO := 'FEMININO';
         
         V_COUNT_FEM := V_COUNT_FEM + V_COUNT_FEM;
      END IF;
      
      -- IF STATUS
      IF R_FUNC.ID_STATUS = 1 THEN
         V_STATUS := 'ATIVO';
         
      ELSE IF R_FUNC.ID_STATUS = 2 THEN
         V_STATUS := 'INATIVO';
      ELSE
         V_STATUS := 'INDEFINIDO';
      END IF;
      
      --- DBMS_OUTPUT.PUT_LINE('NOME É : '||V_NOME|| '  ' || V_SITUACAO);
    
      --- INSERINDO OS DADOS NA TABELA PESSOAS SEM EXCEPTION
      BEGIN
         INSERT INTO PESSOAS VALUES(R_FUNC.NM_FUNCIONARIO, V_GENERO, V_STATUS, V_USUARIO, V_DATA);
      END;
    
      V_COUNT := V_COUNT + V_COUNT;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('FIM DA OPERACAO');

END;

--- CREATE TABLE PESSOAS(NM_PESSOA VARCHAR(100), GENERO VARCHAR(30), STATUS VARCHAR(30), USUARIO VARCHAR(30), DAT_SISTEMA DATE);

--- SELECT * FROM PESSOAS;

--- USUARIO   = USUARIO PEGAMOS NO SELECT
--- DAT_SISTEMA  = DATA DO SISTEMA
--- VARIAVEL AO SAIR DO LOOP QUANTOS REGISTROS FORAM COMPUTADOS:
--- FEMININOS
--- MASCULINOS
--- TOTAL